In [10]:
import numpy as np
a=np.array([[1,2,3,3,1],[6,8,11,10,7]])
a=a.T
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [11]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [12]:
a_centered = a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [14]:
a1=a_centered[:,0]
a2=a_centered[:,1]
a_centered_sp=np.dot(a1,a2)
print(a_centered_sp)

8.0


In [18]:
N=a.shape[0]
N

5

In [19]:
c=a_centered_sp/(N-1)
print(c)

2.0


In [20]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])